### ISSUE TITLE
On import, proteins with multiple possible matches are not sorted to the top of the list

### ISSUE THREAD

**Issue by jacp1** [RBVI/stringApp#12]
If I past a list of IDs into 'Import Network from Public databases -> String protein query' I get the warning "Multiple possible matches found for some terms".  The table shows hundreds of IDs (possibly all the ones in my import list), with the small number of multiple match cases spread through the list. This means I have to click on hundreds of IDs to find the 3 or 4 that have issues. These should either be at the top, or be the only ones displayed.

**Comment by scaramonche** [comment]
This got changed eventually and now only the ones that need resolving are shown.
