### ISSUE TITLE
Changing the chart settings for enrichment results automatically resets STRING style 

### ISSUE THREAD

**Issue by khanspers** [RBVI/stringApp#18]
Here's what I did:

1. Change string network style to default to remove string style, make some changes to node style, including adding a mapping for node fill color.
2. Run String enrichment on string network
3. Filter enrichment results
4. Change the chart settings (for example from split donut to pie chart)
-> Some aspects of the String style are enabled, including String glass ball effect and chemical structures, effectively overwriting the previously defined mappings for fill color.

Note: The style is not updated until the Settings are updated. Simply applying the default chart works fine and the style remains. But whenever the Settings are updated, the String style is enabled.

**Comment by scaramonche** [comment]
Thanks for reporting this, I will have a look!

**Comment by scaramonche** [comment]
This should hopefully be fixed in version 1.7.0.
