### ISSUE TITLE
stringify -- how to deal with unmappable nodes

### ISSUE THREAD

**Issue by scaramonche** [RBVI/stringApp#25]
Currently, if unmappable nodes are kept, we map all nodes with blank "ID" from the user-chosen column to one single node. We should fix that by using the node SUID instead of "ID" or "name" when creating the internal HashMap. If unmappable nodes should be kept, we will copy all rows from the original network to the STRING network. For each node with a blank "ID", we will copy their "name" to the "name" column in the STRING network. 
Additionally, we will add a drop-down menu with all attributes that could be used as "display name" and let the user choose which column to use for displaying names.

**Comment by scootermorris** [comment]
Done, on feature/unmapped-stringify branch.  Ready for testing.

**Comment by scaramonche** [comment]
Tested, added some extras and merged to master.
