### ISSUE TITLE
Saving Enrichment Result

### ISSUE THREAD

**Issue by wangshun1121** [RBVI/stringApp#3]
I have tried this App and tried the enrichment analysis, it'a amazing! But when I finished working, and click File→Export→Tables, I can't find the choice of "STRING enrichment". Then how can I save Enrichment result from this App?
OS: Win7 64bit, CytoScape: 3.5.0, stringApp: 1.1.1

**Comment by wangshun1121** [comment]
I tried CytoScape: 3.3.0, String enrichment Table still can't be saved!

**Comment by scaramonche** [comment]
The functionality to save the STRING tables is not available yet. It is on the list of planned features and will be included in the app as soon as possible.

**Comment by scaramonche** [comment]
Enrichment export is available in the File -> Export menu in version 1.2.
