### ISSUE TITLE
Network Error (code: 503)

### ISSUE THREAD

**Issue by hector3500** [RBVI/stringApp#46]
Hi, when I try to create a network I keep getting this error. Was just wondering if this is a server side issue or is an issue on my end?

![Screenshot from 2023-10-30 17-20-02](https://github.com/RBVI/stringApp/assets/144957696/663330cb-c986-42c7-9923-4caf818c4534)

Thanks.

**Comment by scaramonche** [comment]
Hey! Yes, it is a server-side issue and I hope we will be able to fix it sometime today.

**Comment by scaramonche** [comment]
It should be working again!

**Comment by hector3500** [comment]
Yep working brilliant now, thankyou.
